### ISSUE TITLE
Problem with Ender Storage

### ISSUE THREAD

**Issue by 92Werewolf** [CommodoreThrawn/strawgolem#12]
Hi, the Golem works fine with vanilla chest, but if you try to use a modded chest (like ender storage), the golem stand in front of it and don't put anything inside.
I've tryed with and without the farmland around the chest, but the only way to unstuck him is push it in the direction of the chest, then the golem put the crop inside.
I've attached some screenshots to show you the problem, I use 1.15.2 last version.
Thanks, it's a very usefull and beautifull mod in a magic modpack.

![2020-09-02_14 52 09](https://user-images.githubusercontent.com/70644302/91986711-55fa4e00-ed2d-11ea-93e9-fea8dbcc947e.png)
![2020-09-02_14 52 16](https://user-images.githubusercontent.com/70644302/91986759-68748780-ed2d-11ea-8d94-4d8abba78955.png)
![2020-09-02_14 52 18](https://user-images.githubusercontent.com/70644302/91986770-6d393b80-ed2d-11ea-85e1-b4fd1d7e5ead.png)

**Comment by daPoseidonGuy** [comment]
Ok, so just to confirm - he does place it if you nudge him towards it?

I'll have this fixed for the next release!

**Comment by 92Werewolf** [comment]
Yes, he place if you nudge him near the chest.

**Comment by daPoseidonGuy** [comment]
[fix.zip](https://github.com/daPoseidonGuy/strawgolem/files/5178274/fix.zip)
Does this fix the issue?

**Comment by 92Werewolf** [comment]
Hi, i can't test because it's a 1.16 version, and there isn't "ender chest" mod in this version of minecraft. It's possible to have the 1.15 version fix?

**Comment by CommodoreThrawn** [comment]
Here you go. Sorry about sending the wrong version

[strawgolem-1.15.2-1.9-beta-2.zip](https://github.com/CommodoreThrawn/strawgolem/files/5184966/strawgolem-1.15.2-1.9-beta-2.zip)

**Comment by 92Werewolf** [comment]
Thanks, now sometimes the Golem put correctly the item in the ender chest, but most of the time I must nudge him.

**Comment by CommodoreThrawn** [comment]
[strawgolem-1.15.2-1.9-beta-2.zip](https://github.com/CommodoreThrawn/strawgolem/files/5192187/strawgolem-1.15.2-1.9-beta-2.zip)

Ok, incremented the target distance a bit further again. Try now and let me know if it works reliably?

**Comment by 92Werewolf** [comment]
Perfect, now it works, I've tested for about 10 minutes and the golem always put the items in the ender storage chest. Thanks good work.

**Comment by viniciusdel** [comment]
Hello! I am on the newest version, which is supposed to have this fixed, but they stand in front of the chest without delivering the item. When nudged forward they deliver it.
