### ISSUE TITLE
Golems get stuck at chests

### ISSUE THREAD

**Issue by pinapll** [CommodoreThrawn/strawgolem#13]
I've noticed that if I have any block next to the golem's targeted chest (including a chest next to a chest or a double chest even) the golems will inevitably get stuck standing just pixels too far away from the chest to deposit their items. I ended up with all 6 of my golems just huddled around my double chest yesterday holding crops, not moving at all. Once I nudged them closer, they deposited their crops successfully, but they went back to being stuck some time after.
I don't know much about coding at all, but my best guess is that their path-finding is experiencing difficulties when there's any blocks near or in front of their target chest or crop. I also had a golem completely stuck on a cobble fence because it was in front of a pumpkin that it was desperately trying to make a beeline for. I had to remove the fence before the golem could complete his task. 
For the time being I've removed all potential obstacles and left only singular chests with free space surrounding them, which works fine but the issue with what I assume is their path-finding still exists.

For reference, I am using the latest version: strawgolem-1.16.2-1.9-beta-2.

**Comment by daPoseidonGuy** [comment]
Yea, this should be fixed with the latest commit. I've uploaded a compiled version here for you to verify. 
[fix.zip](https://github.com/daPoseidonGuy/strawgolem/files/5178273/fix.zip)
